jsf:
  project-stage: development
  primefaces:
    theme: bootstrap
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: somepassword